### ISSUE TITLE
Unexpected token { in fs-extra dependency

### ISSUE THREAD

**Issue by DitmirH** [wswebcreation/wdio-cucumberjs-json-reporter#25]
**Environment (please complete the following information):**
 - **Node.js version:** [8]
 - **NPM version:** [6.4.1]
 - **webdriver.io version:** [5.22.4]

When trying to run the tests today ,the following error message appears. I did a clean npm install but it seems to be an issue with the fs-extra dependency in the try() 

To reproduce. , i did rm -rf for node_modules and package-lock , then npm install and re-ran the tests. Latest changes to wdio json package has broken 

[0-0] 2020-04-06T12:23:02.947Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-04-06T12:23:03.250Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialise "wdio-cucumberjs-json-reporter".
/Users/ditmir/Documents/xxxxxx/xxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/wdio-cucumberjs-json-reporter/node_modules/fs-extra/lib/ensure/symlink-type.js:22
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ditmir/Documents/xxxxxxx/xxxxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/wdio-cucumberjs-json-reporter/node_modules/fs-extra/lib/ensure/symlink.js:14:22)
    at safeRequire (/Users/ditmir/Documents/xxxxxxx/xxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/@wdio/utils/build/utils.js:128:11)
    at initialisePlugin (/Users/ditmir/Documents/xxxxxx/xxxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/@wdio/utils/build/initialisePlugin.js:26:41)
    at BaseReporter.initReporter (/Users/ditmir/Documents/xxxxxxx/xxxxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/@wdio/runner/build/reporter.js:120:51)
    at Array.map (<anonymous>)
    at new BaseReporter (/Users/ditmir/Documents/xxxxx/xxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/@wdio/runner/build/reporter.js:32:39)
    at Runner.run (/Users/ditmir/Documents/xxxxxx/xxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/@wdio/runner/build/index.js:77:21)
    at process.on.m (/Users/ditmir/Documents/xxxxxx/xxxxxxxx.FrontEnd.BackofficeUI.tests/test/node_modules/@wdio/local-runner/build/run.js:37:20)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
[0-0] FAILED

Package JSON
    "devDependencies": {
        "@babel/core": "^7.7.2",
        "@babel/preset-env": "^7.7.1",
        "@babel/register": "^7.7.0",
        "@percy/webdriverio": "^1.0.4",
        "@wdio/allure-reporter": "^5.16.0",
        "@wdio/cli": "^5.16.0",
        "@wdio/cucumber-framework": "^5.16.0",
        "@wdio/junit-reporter": "^5.18.6",
        "@wdio/local-runner": "^5.16.1",
        "@wdio/spec-reporter": "^5.15.2",
        "@wdio/sync": "^5.16.0",
        "chromedriver": "^78.0.1",
        "cucumber-pretty": "^6.0.0",
        "wdio-chromedriver-service": "^5.0.2",
        "wdio-cucumberjs-json-reporter": "^1.2.0"
    },
    "dependencies": {
        "@babel/plugin-transform-runtime": "^7.6.2",
        "@babel/runtime": "^7.7.2",
        "@wdio/selenium-standalone-service": "^5.15.0",
        "allure-commandline": "^2.13.0",
        "chai": "^4.2.0",
        "cucumber": "^6.0.3",
        "cucumber-html-reporter": "^5.0.2",
        "fs-extra": "^8.1.0",
        "i": "^0.3.6",
        "mkdirp": "^0.5.1",
        "moment": "^2.24.0",
        "multiple-cucumber-html-reporter": "^1.13.1",
        "npm": "^6.13.0",
        "selenium-standalone": "^6.16.0",
        "wdio-allure-reporter": "^0.8.3"
    }

**Comment by DitmirH** [comment]
Realised NVM had reverted to an older version of NODE . this was resolved by updating  nodejs. 12.6+
