### ISSUE TITLE
Support for wdio7

### ISSUE THREAD

**Issue by fogrizovic** [wswebcreation/wdio-cucumberjs-json-reporter#44]
**Environment (please complete the following information):**
 - **Node.js version:** [14.15.4]
 - **NPM version:** [6.14.10]
 - **webdriver.io version:** [7.0.1]
 - **@wdio/cucumber-framework version:** [7.0.1]
 - **wdio-cucumberjs-json-reporter version:** [2.0.2]

**Describe the bug**
I migrated from wdio6 to wdio7 and I got the following:

[0-18] 2021-02-10T17:37:00.773Z ERROR @wdio/runner: TypeError: Cannot read property 'split' of undefined at CucumberJsJsonReporter.getStepDataObject (/project/node_modules/wdio-cucumberjs-json-reporter/build/reporter.js:314:35) at CucumberJsJsonReporter.addStepData (/project/node_modules/wdio-cucumberjs-json-reporter/build/reporter.js:361:54) at CucumberJsJsonReporter.onHookStart (/project/node_modules/wdio-cucumberjs-json-reporter/build/reporter.js:124:17) at CucumberJsJsonReporter.<anonymous> (/project/node_modules/@wdio/reporter/build/index.js:71:18) at CucumberJsJsonReporter.emit (events.js:315:20) at CucumberJsJsonReporter.EventEmitter.emit (domain.js:467:12) at /project/node_modules/@wdio/runner/build/reporter.js:36:56 at Array.forEach (<anonymous>) at BaseReporter.emit (/project/node_modules/@wdio/runner/build/reporter.js:36:25) at CucumberReporter.emit (/project/node_modules/@wdio/cucumber-framework/build/reporter.js:194:24) at CucumberReporter.handleBeforeStep (/project/node_modules/@wdio/cucumber-framework/build/reporter.js:57:14) at CucumberEventListener.emit (events.js:315:20) at CucumberEventListener.EventEmitter.emit (domain.js:467:12) at CucumberEventListener.onTestStepStarted (/project/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:280:14) at EventEmitter.<anonymous> (/project/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:40:22) at EventEmitter.emit (events.js:327:22) [0-18] Error: Cannot read property 'split' of undefined

**Comment by wswebcreation** [comment]
Thanks for filing a bug, I will take a look at it this weekend hope hope to fix it asap, unless you have some time for a PR 😜

**Comment by wswebcreation** [comment]
Hi @fogrizovic 

I found the bug and fixed it, I only need to get in contact with the WDIO team because more seems to be broken in V7. You can now use version [`2.0.3`](https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v2.0.3), see the comments in the changelog.

Closing it for now, but feel free to open it when you are still facing issues

**Comment by fogrizovic** [comment]
Hi @wswebcreation . I tried the update and worked fine.
Yes, i'm getting some other errors but from wdio, not this plugin.

thanks!

**Comment by wswebcreation** [comment]
Thanks for the feedback
