### ISSUE TITLE
uri property for feature objects

### ISSUE THREAD

**Issue by senovsky** [wswebcreation/wdio-cucumberjs-json-reporter#7]
**Is your feature request related to a problem? Please describe.**
Back when I was using [cucumber-boilerplate](https://github.com/webdriverio/cucumber-boilerplate) with WDIO v4, I was feeding the JSON from [wdio-multiple-cucumber-html-reporter](https://www.npmjs.com/package/wdio-multiple-cucumber-html-reporter) to [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) (because I needed single-file single-page HTML report). That no longer works because the uri property is missing and I'm getting this error:
```
C:\Users\something\e2e\node_modules\cucumber-html-reporter\lib\hierarchyReporter.js:22
        var uriParts = feature.uri.split(path.sep);
                                   ^

TypeError: Cannot read property 'split' of undefined
    at C:\Users\something\e2e\node_modules\cucumber-html-reporter\lib\hierarchyReporter.js:22:36
    at Array.forEach (<anonymous>)
    at Object.getBaseDir (C:\Users\something\e2e\node_modules\cucumber-html-reporter\lib\hierarchyReporter.js:21:20)
    at setStats (C:\Users\something\e2e\node_modules\cucumber-html-reporter\lib\reporter.js:200:41)
    at generateReport (C:\Users\something\e2e\node_modules\cucumber-html-reporter\lib\reporter.js:420:13)
    at Object.generate (C:\Users\something\e2e\node_modules\cucumber-html-reporter\lib\reporter.js:466:9)
    at Object.generateReport [as generate] (C:\Users\something\e2e\node_modules\cucumber-html-reporter\index.js:30:21)
    at Object.<anonymous> (C:\Users\something\e2e\index.js:19:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**Describe the solution you'd like**
Would it be possible to add the uri property to the feature objects, pretty please? :-)

**Describe alternatives you've considered**
I don't know about any other single-page singe-file HTML reports creating package.

**Comment by wswebcreation** [comment]
Sorry, also didn't see this one, I can't determine the current file anymore with WebdriverIO V5, so I added it so it will not break anymore for you.

Please check https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.0.8 and close the issue if it is fixed now for you

**Comment by senovsky** [comment]
Even though the uri line in the json reads "Can not be determined", it's enough for cucumber-html-reporter to create the HTML report :-D So we can consider this issue resolved.

**Comment by wswebcreation** [comment]
Tnx for closing
